fixes #156 - implement rp_launch_id parameter to specify an existing launch to be used by the session
reportportal/agent-python-pytest pull request #240
Opened 2020-11-19 19:44 UTC by rplevka

**depends on**: https://github.com/reportportal/client-Python/pull/133

This implements the RFE #156 - we're now able to specify `--rp_launch_id <launch uuid>` cli option(or `launch_id` option in `pytest.ini`) to be used by the RP logger.
When used, the logger doesn't control the launch (start/finish) and we're free to control it by external script (e.g. jenkins pipeline).

Since this depends on https://github.com/reportportal/client-Python/pull/133 to be merged and released, this PR should also include the bumped version of the client-Python package in `requirements.txt`.

2020-11-20 09:12 UTC, iivanou commented on pytest_reportportal/plugin.py
> +        if not session.config.getini('rp_launch_id'):
It's better to track this condition in the client rather than implementing the same "if" statements in every agent.

2020-11-23 09:55 UTC, iivanou requested changes

2020-11-23 09:55 UTC, iivanou commented on pytest_reportportal/service.py
> +        self.custom_launch = None
What is the purpose of this attribute? It's not used in the service object...

2020-11-23 09:55 UTC, iivanou commented on pytest_reportportal/service.py
> +                launch_id=self.custom_launch
Just pass directly `custom_launch`  from options.

2020-11-26 11:08 UTC, rplevka commented on pytest_reportportal/service.py
> +                launch_id=self.custom_launch
done

2020-11-26 11:48 UTC, iivanou approved these changes

2020-11-26 13:11 UTC, merged