Add rp_mode to pytest.ini
reportportal/agent-python-pytest pull request #280
Opened 2021-09-02 16:22 UTC by kevin-henry-fernride

2021-09-02 16:28 UTC, iivanou requested changes

2021-09-02 16:28 UTC, iivanou commented on pytest_reportportal/config.py
> +        self.rp_parent_item_id = (self.pconfig.option.rp_parent_item_id or
Please, use the find_option method. Rebase against the master.

2021-09-02 16:28 UTC, iivanou commented on pytest_reportportal/service.py
> +            return test_item.reportinfo()[2]
Add a new line at the end of the file.

2021-09-02 16:28 UTC, iivanou commented on pytest_reportportal/service.py
> +            if hasattr(test_item, "obj"):
Please, add a unit test for this method.

2021-12-02 14:29 UTC, HardNorth commented
Abandoned

2021-12-02 14:29 UTC, closed without merging