Adds support to have attributes with same keys
reportportal/agent-python-pytest pull request #283
Opened 2021-11-03 19:14 UTC by san7ket

Report Portal supports having Attributes with same keys. This is important when filtering data on dashboards and having similar attributes on same level. Also helpful in group tests. 

New Contributor Alert, Please let me know, if there is anything I missed or need to do to have pr reviewed

2021-11-04 09:00 UTC, iivanou requested changes
Please, add unit tests for this.

2021-11-04 09:03 UTC, iivanou commented
Existing unit test require modifications as well.

2021-11-15 10:53 UTC, san7ket commented
Sorry was away on vacation, will work on comments. thank you.

2021-11-16 08:37 UTC, san7ket commented
@iivanou resolved comments and fixed unit tests.

2021-11-17 12:58 UTC, iivanou commented
@san7ket Tests still have not passed...

2021-11-18 19:19 UTC, san7ket commented
> @san7ket Tests still have not passed...

So if I understand this correct tests are failing for Python3.6 right ? I need to create a dev env for 3.6 and test ?

2021-11-18 19:28 UTC, san7ket commented
> @san7ket Tests still have not passed...

Fixed the flake8 issues, tox now succeeds on py36

2021-11-29 11:13 UTC, san7ket commented
@iivanou tested on py36 , tests should now pass

2021-12-02 14:35 UTC, HardNorth approved these changes
Looks OK-ish for me

2021-12-03 10:17 UTC, iivanou approved these changes

2021-12-03 10:17 UTC, merged